apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bw-cert 
spec:
  secretName: bw-cert
  commonName: bitwarden.matthew-cloud.com
  dnsNames:
    - bitwarden.matthew-cloud.com
  issuerRef:
    name: cf-dns
    kind: ClusterIssuer
    group: cert-manager.io
